sonar.projectKey=at1234-sectionb-2026-calendar-levlimit
sonar.projectName=at1234-sectionb-2026-calendar-levlimit
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts
sonar.cpd.exclusions=**/*.spec.ts,**/*.test.ts
